Name: Greeshma Hedvikar

Net ID- gh2461

Assignment- 02

In [1]:
import numpy as np

# Load the iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [2]:
# Define two numpy arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[4, 5, 6], [7, 8, 9]])

# Stack vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
Horizontal Stack:
 [[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [3]:
# Find common elements
common_elements = np.intersect1d(A, B)
print("Common Elements between A and B:", common_elements)


Common Elements between A and B: [4 5 6]


In [4]:
# Extract elements between 5 and 10 from A
range_elements = A[(A >= 5) & (A <= 10)]
print("Elements between 5 and 10 from A:", range_elements)


Elements between 5 and 10 from A: [5 6]


In [5]:
# Filter rows based on conditions
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d rows:\n", filtered_rows)


Filtered iris_2d rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [6]:
import pandas as pd

# Load dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Select every 20th row starting from 0 for selected columns
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:
# Reload dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replace NaNs with column mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print("Missing values filled in Min.Price and Max.Price.")


Missing values filled in Min.Price and Max.Price.


<ipython-input-7-cb0198c93101>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-7-cb0198c93101>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'

In [8]:
# Create a random DataFrame
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Filter rows where row sum > 100
rows_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]
print("Rows with sum > 100:\n", rows_sum_gt_100)


Rows with sum > 100:
      0   1   2   3
1   11  20  39  35
7   12  25  35  37
10  27  39  30  14
12  29  33  20  36
